#!/usr/bin/env bash

{
	cat <<-'EOH'
	# This file lists all individuals having contributed content to the ALX SE AirBnB Clone project.
	# For how it is generated, see `generate-authors`
	EOH
	echo
	git log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf
} > AUTHORS
