#!/usr/bin/python3
"""Defines a class <Place>."""
from models.base_model import BaseModel


class Place(BaseModel):
    """A class <Place> that inherits from <BaseModel>.

    Public class attributes:
        city_id (str): ...
        user_id (str): ...
        name (str): ...
        description (str): ...
        number_of_rooms (int): ...
        number_bathrooms (int): ...
        max_guest (int): ...
        price_by_night (int): ...
        latitude (float): ...
        longitude (float): ...
        amenity_ids (list): ...
    """

    city_id = str()
    user_id = str()
    name = str()
    description = str()
    number_of_rooms = int()
    number_bathrooms = int()
    max_guest = int()
    price_by_night = int()
    latitude = float()
    longitude = float()
    amenity_ids = list()
